[package]
name = "klippy"
version.workspace = true
edition.workspace = true
license.workspace = true
include = ["/src"]

[dependencies]
anyhow.workspace = true
clap.workspace = true
pyo3 = { workspace = true }
tokio = { workspace = true, features = ["net", "time"] }
tracing.workspace = true
tracing-journald.workspace = true
tracing-subscriber.workspace = true
